services:

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "50011:8080"
    environment:
      - WEBUI_AUTH=false
      - OPENAI_API_BASE_URL=http://bifrost:8080/v1
      - OPENAI_API_KEY=sk-secret
    volumes:
      - ./data/openwebui:/app/backend/data
    depends_on:
      - bifrost
    restart: always
    networks:
      - llmnet

  bifrost:
    image: maximhq/bifrost:latest
    container_name: bifrost_app
    ports:
      - "50012:8080"
    volumes:
      - ./config.json:/app/config.json
      - ./data/bifrost:/app/data
    restart: always
    networks:
      - llmnet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "50013:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
    restart: always
    networks:
      - llmnet

networks:
  llmnet:
    driver: bridge

volumes:
  prometheus_data:
    driver: local